name: Publish Python 🐍 distribution 📦 to PyPI 

on:
  # release:
  #   types: [published]
  push:
    tags: 
      - "*"

jobs:
  test-package:
    # uses: ./.github/workflows/python-test.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v7
      with:
        workflow: python-test.yml
        workflow_conclusion: success
        branch: ${{ github.event.base_ref }}
        name: test-results
        path: test_results/
    - name: Check test result for the branch
      id: check_test
      run: pymob/bash/validate_test_results.sh test_results ${{ github.event.base_ref }}
  build-package:
    needs: test-package
    uses: ./.github/workflows/python-build.yml
  publish-package:
    name: Publish Python 🐍 distribution 📦 to PyPI

    needs: build-package

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pymob 
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download artifact
      id: download-artifact
      # make sure you use the same version for uploading and downloading artifacts
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
