name: Build Python 🐍 package 📦 

on:
  workflow_call:
  workflow_dispatch:

env:
  # not strictly necessary here, because the job will only be triggered by a push (ref_name)
  branch_name: ${{ github.head_ref || github.ref_name }} 
    
jobs:
  check-test-results:
    name: ✔ Check test results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: 👇 Download test result artifact python
      uses: actions/download-artifact@v4
      with:
        name: test-result-${{ env.branch_name }}-${{ matrix.python-version }}
        path: .

    - name: ✔ Check test result
      id: check-test-result
      run: |
        if [[ -f test_result.txt && $(cat test_result.txt) == "success" ]]; then
          echo "Tests passed"
        else
          echo "Tests failed"
          exit 1
        fi
      
  build:
    name: Build distribution 📦
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 🖥️ Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: 🔧 Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build
      
    - name: 📁 Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
