name: Publish Python 🐍 distribution 📦 to PyPI 

on:
  # release:
  #   types: [published]
  push:
    tags: 
      - "*"

jobs:
  publish-package:
    name: Publish Python 🐍 distribution 📦 to PyPI

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pymob 
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: python-build.yml
        workflow_conclusion: success
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
