name: Build Python 🐍 package 📦 

on:
  workflow_call:
  workflow_dispatch:

env:
  # not strictly necessary here, because the job will only be triggered by a push (ref_name)
  branch_name: ${{ github.head_ref || github.ref_name }} 
    
jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        # see more contexts: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        run: |
          echo "Branch name ${{ env.branch_name }}"
          echo "GitHub actor: ${{ github.actor }}"
          echo "GitHub workflow: ${{ github.workflow }}"
          echo "GitHub action: ${{ github.action }}"
          echo "GitHub run_ID: ${{ github.run_id }}"
          echo "GitHub event_name: ${{ github.event_name }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub ref_type: ${{ github.ref_type }}"
          echo "GitHub ref_name: ${{ github.ref_name }}"
          echo "GitHub sha: ${{ github.sha }}"
  
      
  build:
    name: Build distribution 📦
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 🖥️ Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    
    - name: 🔧 Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build
      
    - name: 📁 Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
